version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
      - ../mydata:/workspaces/${localWorkspaceFolderBasename}/mydata
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - psql-data:/tmp/dev/pgsql/data
      - ./setup.sh:/setup.sh # Mount the setup.sh script into the container
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      #- "${POSTGRES_PORT}:5432"
      - "5432:5432"
    #entrypoint: ["/bin/sh", "-c", "until pg_isready -h localhost -p 5432 -U postgres; do sleep 2; done && /setup.sh && /usr/local/bin/docker-entrypoint.sh postgres"]
    
    #entrypoint: ["/bin/sh", "/setup.sh"]  # Use custom entrypoint


  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pga-data:/tmp/dev/pga/data
      #- data-share-volume:/data-share
      - ./setup.sh:/setup.sh # Mount the setup.sh script into the container
    ports:
      - "5555:80"
    depends_on:
      - postgres
    # command:
    #   ["sh", "-c", "./setup.sh && exec /usr/local/bin/docker-entrypoint.sh"]

  kestra:
    image: kestra/kestra:latest
    env_file:
      - .env
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            # username: kestra
            # password: k3str4
        kestra:
          server:
            basicAuth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
volumes:
  psql-data:
  pga-data:
  kestra-data: